base_dir: log/conv2d/
data:
  batch_size: 200
<<<<<<< HEAD
  dataset: ../drive/My Drive/conv2d_gsmap.npz
  # dataset: data/conv2d_gsmap/npz/conv2d_gsmap.npz
  gauge_dataset: data/conv2d_gsmap/npz/gauge_data.npz
=======
  dataset: /content/drive/My Drive/map_gauge_72_stations.npz
  dataset1: data/npz/correlation.npz
>>>>>>> origin/correlation
  test_batch_size: 1
  test_size: 0.2
  valid_size: 0.2
log_level: INFO
model:
  rnn_units: 100
  activation: relu
  seq_len: 4
<<<<<<< HEAD
  horizon: 1
=======
  horizon: 0
>>>>>>> origin/correlation
train:
  dropout: 0
  epochs: 300
  optimizer: adam
  patience: 15
  loss: mse

